# Generated by Django 5.0.2 on 2024-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=200)),
                ('receipe_description', models.TextField(max_length=500)),
                ('receipe_image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
